
import java.util.*;
class number
{
   int g;
   int n;
   public double per;
   number(int s)
   {
    g=s;
   }  
   void input()
   {
     
    Scanner sc=new Scanner(System.in);
    System.out.println("random number:");
    n=sc.nextInt();
   
    }
    void output()
    {
     System.out.println("Number generated by computer is :"+g);
    }
    
    void computer()
    { 
     
     if(n==g)
       {
          System.out.println("Number is guess Sccuessfully");
          per=n/(g*0.01);
          System.out.println("Score :"+per+"%");
          
       }
       if(n!=g)
       {
            System.out.println("Number is Wrong");
       
               
               if(n>=40 && n<=50)
               {if(g>50 && g<=60)
       		{
       		System.out.println("Number is higher than 51 and lower than equal to 60");
       		}
       		if(g>60 &&  g<=70)
       		{
        	System.out.println("Number is higher than 61 and lower than equal to 70");
       		}
       		if(g>70 &&  g<=80)
       		{
        	System.out.println("Number is higher than 71 and lower than equal to 80");
       		}	
		if(g>80 &&  g<=90)
       		{
        	System.out.println("Number is higher than 81 and lower than equal to 90");
       		}
       		if(g>90 && g<=100)
       		{
        	System.out.println("Number is higher than 91 and lower than equal to 100");
       		}
        	if(g>=40 && g<=50)
       		{
        	System.out.println("Number is higher than equal to 40 and lower than equal to 50");
       		}
                if(g>=30 && g<40 )
       		{
        	System.out.println("Number is higher than equal to 30 and lower than equal to 39");
       		}	
       		if(g>=20 && g<30)
       		{
        	System.out.println("Number is higher than equal to 20 and lower than equal to 29");
       		}
       		if(g>=10 && g<20)
                {
                System.out.println("Number is higher than equal to 10 and lower than equal to 19");
                }
                if(g>=1 && g<10)
                {
                System.out.println("Number is higher than equal to 1 to lower than equal to 9");
       		}
                if(n<=g)
		{
		per=n/(g*0.01);
                System.out.println("Score:"+per+"%");
		}
                else
		{
		per=(n/(g*0.01))-100;
                System.out.println("Score:"+per+"%");
		}
		
	       }
	       if(n>=30 && n<40)
               {if(g>50 && g<=60)
       		{
       		System.out.println("Number is higher than 51 and lower than equal to 60");
       		}
       		if(g>60 &&  g<=70)
       		{
        	System.out.println("Number is higher than 61 and lower than equal to 70");
       		}
       		if(g>70 &&  g<=80)
       		{
        	System.out.println("Number is higher than 71 and lower than equal to 80");
       		}	
		if(g>80 &&  g<=90)
       		{
        	System.out.println("Number is higher than 81 and lower than equal to 90");
       		}
       		if(g>90 && g<=100)
       		{
        	System.out.println("Number is higher than 91 and lower than equal to 100");
       		}
        	if(g>=40 && g<=50)
       		{
        	System.out.println("Number is higher than equal to 40 and lower than equal to 50");
       		}
                if(g>=30 && g<40 )
       		{
        	System.out.println("Number is higher than equal to 30 and lower than equal to 39");
       		}	
       		if(g>=20 && g<30)
       		{
        	System.out.println("Number is higher than equal to 20 and lower than equal to 29");
       		}
       		if(g>=10 && g<20)
                {
                System.out.println("Number is higher than equal to 10 and lower than equal to 19");
                }
                if(g>=1 && g<10)
                {
                System.out.println("Number is higher than equal to 1 to lower than equal to 9");
       		}
		
		if(n<=g)
		{
		per=n/(g*0.01);
                System.out.println("Score:"+per+"%");
		}
                else
		{
		per=(n/(g*0.01))-100;
                System.out.println("Score:"+per+"%");
		}
	       }
	       if(n>=20 && n<30)
               {if(g>50 && g<=60)
       		{
       		System.out.println("Number is higher than 51 and lower than equal to 60");
       		}
       		if(g>60 &&  g<=70)
       		{
        	System.out.println("Number is higher than 61 and lower than equal to 70");
       		}
       		if(g>70 &&  g<=80)
       		{
        	System.out.println("Number is higher than 71 and lower than equal to 80");
       		}	
		if(g>80 &&  g<=90)
       		{
        	System.out.println("Number is higher than 81 and lower than equal to 90");
       		}
       		if(g>90 && g<=100)
       		{
        	System.out.println("Number is higher than 91 and lower than equal to 100");
       		}
        	if(g>=40 && g<=50)
       		{
        	System.out.println("Number is higher than equal to 40 and lower than equal to 50");
       		}
                if(g>=30 && g<40 )
       		{
        	System.out.println("Number is higher than equal to 30 and lower than equal to 39");
       		}	
       		if(g>=20 && g<30)
       		{
        	System.out.println("Number is higher than equal to 20 and lower than equal to 29");
       		}
       		if(g>=10 && g<20)
                {
                System.out.println("Number is higher than equal to 10 and lower than equal to 19");
                }
                if(g>=1 && g<10)
                {
                System.out.println("Number is higher than equal to 1 to lower than equal to 9");
       		}
		
		if(n<=g)
		{
		per=n/(g*0.01);
                System.out.println("Score:"+per+"%");
		}
                else
		{
		per=(n/(g*0.01))-100;
                System.out.println("Score:"+per+"%");
		}
	       }
	       if(n>=10 && n<20)
               {if(g>50 && g<=60)
       		{
       		System.out.println("Number is higher than 51 and lower than equal to 60");
       		}
       		if(g>60 &&  g<=70)
       		{
        	System.out.println("Number is higher than 61 and lower than equal to 70");
       		}
       		if(g>70 &&  g<=80)
       		{
        	System.out.println("Number is higher than 71 and lower than equal to 80");
       		}	
		if(g>80 &&  g<=90)
       		{
        	System.out.println("Number is higher than 81 and lower than equal to 90");
       		}
       		if(g>90 && g<=100)
       		{
        	System.out.println("Number is higher than 91 and lower than equal to 100");
       		}
        	if(g>=40 && g<=50)
       		{
        	System.out.println("Number is higher than equal to 40 and lower than equal to 50");
       		}
                if(g>=30 && g<40 )
       		{
        	System.out.println("Number is higher than equal to 30 and lower than equal to 39");
       		}	
       		if(g>=20 && g<30)
       		{
        	System.out.println("Number is higher than equal to 20 and lower than equal to 29");
       		}
       		if(g>=10 && g<20)
                {
                System.out.println("Number is higher than equal to 10 and lower than equal to 19");
                }
                if(g>=1 && g<10)
                {
                System.out.println("Number is higher than equal to 1 to lower than equal to 9");
       		}
		
		if(n<=g)
		{
		per=n/(g*0.01);
                System.out.println("Score:"+per+"%");
		}
                else
		{
		per=(n/(g*0.01))-100;
                System.out.println("Score:"+per+"%");
		}
	       }
	       if(n>=1 && n<10)
               {
                
		if(n<=g)
		{
		per=n/(g*0.01);
                System.out.println("Score:"+per+"%");
		}
                else
		{
		per=(n/(g*0.01))-100;
                System.out.println("Score:"+per+"%");
		}
	       }
	       if(n>50 && n<=60)
       	      { if(g>50 && g<=60)
       		{
       		System.out.println("Number is higher than 51 and lower than equal to 60");
       		}
       		if(g>60 &&  g<=70)
       		{
        	System.out.println("Number is higher than 61 and lower than equal to 70");
       		}
       		if(g>70 &&  g<=80)
       		{
        	System.out.println("Number is higher than 71 and lower than equal to 80");
       		}	
		if(g>80 &&  g<=90)
       		{
        	System.out.println("Number is higher than 81 and lower than equal to 90");
       		}
       		if(g>90 && g<=100)
       		{
        	System.out.println("Number is higher than 91 and lower than equal to 100");
       		}
        	if(g>=40 && g<=50)
       		{
        	System.out.println("Number is higher than equal to 40 and lower than equal to 50");
       		}
                if(g>=30 && g<40 )
       		{
        	System.out.println("Number is higher than equal to 30 and lower than equal to 39");
       		}	
       		if(g>=20 && g<30)
       		{
        	System.out.println("Number is higher than equal to 20 and lower than equal to 29");
       		}
       		if(g>=10 && g<20)
                {
                System.out.println("Number is higher than equal to 10 and lower than equal to 19");
                }
                if(g>=1 && g<10)
                {
                System.out.println("Number is higher than equal to 1 to lower than equal to 9");
       		}
		if(n<=g)
		{
		per=n/(g*0.01);
                System.out.println("Score:"+per+"%");
		}
                else
		{
		per=(n/(g*0.01))-100;
                System.out.println("Score:"+per+"%");
		}
	      }
       	      if(n>60 && n<=70)
       	      { if(g>50 && g<=60)
       		{
       		System.out.println("Number is higher than 51 and lower than equal to 60");
       		}
       		if(g>60 &&  g<=70)
       		{
        	System.out.println("Number is higher than 61 and lower than equal to 70");
       		}
       		if(g>70 &&  g<=80)
       		{
        	System.out.println("Number is higher than 71 and lower than equal to 80");
       		}	
		if(g>80 &&  g<=90)
       		{
        	System.out.println("Number is higher than 81 and lower than equal to 90");
       		}
       		if(g>90 && g<=100)
       		{
        	System.out.println("Number is higher than 91 and lower than equal to 100");
       		}
        	if(g>=40 && g<=50)
       		{
        	System.out.println("Number is higher than equal to 40 and lower than equal to 50");
       		}
                if(g>=30 && g<40 )
       		{
        	System.out.println("Number is higher than equal to 30 and lower than equal to 39");
       		}	
       		if(g>=20 && g<30)
       		{
        	System.out.println("Number is higher than equal to 20 and lower than equal to 29");
       		}
       		if(g>=10 && g<20)
                {
                System.out.println("Number is higher than equal to 10 and lower than equal to 19");
                }
                if(g>=1 && g<10)
                {
                System.out.println("Number is higher than equal to 1 to lower than equal to 9");
       		}
		if(n<=g)
		{
		per=n/(g*0.01);
                System.out.println("Score:"+per+"%");
		}
                else
		{
		per=(n/(g*0.01))-100;
                System.out.println("Score:"+per+"%");
		}
	      }
	      if(n>70 && n<=80)
       	      { if(g>50 && g<=60)
       		{
       		System.out.println("Number is higher than 51 and lower than equal to 60");
       		}
       		if(g>60 &&  g<=70)
       		{
        	System.out.println("Number is higher than 61 and lower than equal to 70");
       		}
       		if(g>70 &&  g<=80)
       		{
        	System.out.println("Number is higher than 71 and lower than equal to 80");
       		}	
		if(g>80 &&  g<=90)
       		{
        	System.out.println("Number is higher than 81 and lower than equal to 90");
       		}
       		if(g>90 && g<=100)
       		{
        	System.out.println("Number is higher than 91 and lower than equal to 100");
       		}
        	if(g>=40 && g<=50)
       		{
        	System.out.println("Number is higher than equal to 40 and lower than equal to 50");
       		}
                if(g>=30 && g<40 )
       		{
        	System.out.println("Number is higher than equal to 30 and lower than equal to 39");
       		}	
       		if(g>=20 && g<30)
       		{
        	System.out.println("Number is higher than equal to 20 and lower than equal to 29");
       		}
       		if(g>=10 && g<20)
                {
                System.out.println("Number is higher than equal to 10 and lower than equal to 19");
                }
                if(g>=1 && g<10)
                {
                System.out.println("Number is higher than equal to 1 to lower than equal to 9");
       		}
		if(n<=g)
		{
		per=n/(g*0.01);
                System.out.println("Score:"+per+"%");
		}
                else
		{
		per=(n/(g*0.01))-100;
                System.out.println("Score:"+per+"%");
		}
	      }
	      if(n>80 && n<=90)
       	      { if(g>50 && g<=60)
       		{
       		System.out.println("Number is higher than 51 and lower than equal to 60");
       		}
       		if(g>60 &&  g<=70)
       		{
        	System.out.println("Number is higher than 61 and lower than equal to 70");
       		}
       		if(g>70 &&  g<=80)
       		{
        	System.out.println("Number is higher than 71 and lower than equal to 80");
       		}	
		if(g>80 &&  g<=90)
       		{
        	System.out.println("Number is higher than 81 and lower than equal to 90");
       		}
       		if(g>90 && g<=100)
       		{
        	System.out.println("Number is higher than 91 and lower than equal to 100");
       		}
        	if(g>=40 && g<=50)
       		{
        	System.out.println("Number is higher than equal to 40 and lower than equal to 50");
       		}
                if(g>=30 && g<40 )
       		{
        	System.out.println("Number is higher than equal to 30 and lower than equal to 39");
       		}	
       		if(g>=20 && g<30)
       		{
        	System.out.println("Number is higher than equal to 20 and lower than equal to 29");
       		}
       		if(g>=10 && g<20)
                {
                System.out.println("Number is higher than equal to 10 and lower than equal to 19");
                }
                if(g>=1 && g<10)
                {
                System.out.println("Number is higher than equal to 1 to lower than equal to 9");
       		}
		if(n<=g)
		{
		per=n/(g*0.01);
                System.out.println("Score:"+per+"%");
		}
                else
		{
		per=(n/(g*0.01))-100;
                System.out.println("Score:"+per+"%");
		}
	      }
	      if(n>90 && n<=100)
       	      { if(g>50 && g<=60)
       		{
       		System.out.println("Number is higher than 51 and lower than equal to 60");
       		}
       		if(g>60 &&  g<=70)
       		{
        	System.out.println("Number is higher than 61 and lower than equal to 70");
       		}
       		if(g>70 &&  g<=80)
       		{
        	System.out.println("Number is higher than 71 and lower than equal to 80");
       		}	
		if(g>80 &&  g<=90)
       		{
        	System.out.println("Number is higher than 81 and lower than equal to 90");
       		}
       		if(g>90 && g<=100)
       		{
        	System.out.println("Number is higher than 91 and lower than equal to 100");
       		}
        	if(g>=40 && g<=50)
       		{
        	System.out.println("Number is higher than equal to 40 and lower than equal to 50");
       		}
                if(g>=30 && g<40 )
       		{
        	System.out.println("Number is higher than equal to 30 and lower than equal to 39");
       		}	
       		if(g>=20 && g<30)
       		{
        	System.out.println("Number is higher than equal to 20 and lower than equal to 29");
       		}
       		if(g>=10 && g<20)
                {
                System.out.println("Number is higher than equal to 10 and lower than equal to 19");
                }
                if(g>=1 && g<10)
                {
                System.out.println("Number is higher than equal to 1 to lower than equal to 9");
       		}
		if(n<=g)
		{
		per=n/(g*0.01);
                System.out.println("Score:"+per+"%");
		}
                else
		{
		per=(n/(g*0.01))-100;
                System.out.println("Score:"+per+"%");
		}
	      
	      
		
	      }
       }
     }
    
 }
class game
{
public static void main(String ar[])
{
int rn;
   
//number nc=new number(rn);
System.out.println("*******************Number Guessing Game*************************");
System.out.println("Rules");
System.out.println("1 Enter the Number between 1 to 100");
System.out.println("2 Game contain 3 Round and each Round has 3 attempts");
for(int j=1;j<=3;j++)
{
Random rand=new Random();
rn=rand.nextInt(100);
number nc=new number(rn);
System.out.println("*************Round No "+j+"*****************");
for(int i=1;i<=3;i++)
{
System.out.println("Attempt No "+i+":");
nc.input();
nc.computer();
}

nc.output();


}



}
}